title: ThunderHub
remote_theme: pmarsceill/just-the-docs
aux_links:
  "ThunderHub Repository":
    - "https://github.com/apotdevin/thunderhub"
  "Contribute! Source on GitHub":
    - "https://github.com/apotdevin/thunderhub-docs"
# search_enabled: true
# enable theme for local usage
# theme: "just-the-docs"
